name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install --force
          npm run-script build
#        env:
#          CI: false # Remove CI's "treating warnings as errors flag"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          folder: build # The folder the action should deploy.
